//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyProject.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на card online.
        /// </summary>
        public static string Basket_by_card_online {
            get {
                return ResourceManager.GetString("Basket_by_card_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на card.
        /// </summary>
        public static string Basket_by_card_with_curier {
            get {
                return ResourceManager.GetString("Basket_by_card_with_curier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на card.
        /// </summary>
        public static string Basket_Card {
            get {
                return ResourceManager.GetString("Basket_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cash.
        /// </summary>
        public static string Basket_cash {
            get {
                return ResourceManager.GetString("Basket_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm.
        /// </summary>
        public static string Basket_confirm {
            get {
                return ResourceManager.GetString("Basket_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer name.
        /// </summary>
        public static string Basket_customer_name {
            get {
                return ResourceManager.GetString("Basket_customer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delivery.
        /// </summary>
        public static string Basket_delivery {
            get {
                return ResourceManager.GetString("Basket_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay.
        /// </summary>
        public static string Basket_Pay {
            get {
                return ResourceManager.GetString("Basket_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Payment method.
        /// </summary>
        public static string Basket_payment_method {
            get {
                return ResourceManager.GetString("Basket_payment_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pickup.
        /// </summary>
        public static string Basket_pickup {
            get {
                return ResourceManager.GetString("Basket_pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string Form_exit {
            get {
                return ResourceManager.GetString("Form_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Form_Save {
            get {
                return ResourceManager.GetString("Form_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send.
        /// </summary>
        public static string Form_Send {
            get {
                return ResourceManager.GetString("Form_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string g {
            get {
                return ResourceManager.GetString("g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DISCOVER MENU.
        /// </summary>
        public static string Index_discover_menu {
            get {
                return ResourceManager.GetString("Index_discover_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DISCOVER SPECIAL OFFER.
        /// </summary>
        public static string Index_discover_SO {
            get {
                return ResourceManager.GetString("Index_discover_SO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MAGNOLIA MENU.
        /// </summary>
        public static string Index_Menu {
            get {
                return ResourceManager.GetString("Index_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OUR CAFE.
        /// </summary>
        public static string Index_Our_cafe {
            get {
                return ResourceManager.GetString("Index-Our-cafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SPECIAL OFFER.
        /// </summary>
        public static string Index_Special_offer {
            get {
                return ResourceManager.GetString("Index_Special_offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gkalls annsn flid gof, asalakd fodn okrs ada.
        /// </summary>
        public static string Index_text_1 {
            get {
                return ResourceManager.GetString("Index_text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Goosf kfor asdonrp propr jank.
        /// </summary>
        public static string Index_text_2 {
            get {
                return ResourceManager.GetString("Index_text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на en.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Basket.
        /// </summary>
        public static string Layout_Basket {
            get {
                return ResourceManager.GetString("Layout_Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        public static string Layout_Home {
            get {
                return ResourceManager.GetString("Layout_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log in.
        /// </summary>
        public static string Layout_LogIn {
            get {
                return ResourceManager.GetString("Layout_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu.
        /// </summary>
        public static string Layout_Menu {
            get {
                return ResourceManager.GetString("Layout_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на or.
        /// </summary>
        public static string Layout_or {
            get {
                return ResourceManager.GetString("Layout_or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile.
        /// </summary>
        public static string Layout_Profile {
            get {
                return ResourceManager.GetString("Layout_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string Layout_Registration {
            get {
                return ResourceManager.GetString("Layout_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign in.
        /// </summary>
        public static string Layout_SignIn {
            get {
                return ResourceManager.GetString("Layout_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign out.
        /// </summary>
        public static string Layout_SignOut {
            get {
                return ResourceManager.GetString("Layout_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add to basket.
        /// </summary>
        public static string Menu_add_to_basket {
            get {
                return ResourceManager.GetString("Menu_add_to_basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на login.
        /// </summary>
        public static string Placeholder_login {
            get {
                return ResourceManager.GetString("Placeholder_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на password.
        /// </summary>
        public static string Placeholder_password {
            get {
                return ResourceManager.GetString("Placeholder_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на change avatar.
        /// </summary>
        public static string Profile_change_avatar {
            get {
                return ResourceManager.GetString("Profile_change_avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string Profile_Edit {
            get {
                return ResourceManager.GetString("Profile_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Form.
        /// </summary>
        public static string Profile_Form {
            get {
                return ResourceManager.GetString("Profile_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Leave your review.
        /// </summary>
        public static string Profile_review {
            get {
                return ResourceManager.GetString("Profile_review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на save.
        /// </summary>
        public static string Profile_save {
            get {
                return ResourceManager.GetString("Profile_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check out reviews from our visitors:.
        /// </summary>
        public static string Review_look {
            get {
                return ResourceManager.GetString("Review_look", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Leave your review.
        /// </summary>
        public static string Review_placeholder {
            get {
                return ResourceManager.GetString("Review_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please,.
        /// </summary>
        public static string Review_please {
            get {
                return ResourceManager.GetString("Review_please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на register.
        /// </summary>
        public static string Review_register {
            get {
                return ResourceManager.GetString("Review_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reviews.
        /// </summary>
        public static string Review_review {
            get {
                return ResourceManager.GetString("Review_review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на sign in.
        /// </summary>
        public static string Review_sign_in {
            get {
                return ResourceManager.GetString("Review_sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To leave your review you must be authorized.
        /// </summary>
        public static string Review_warning {
            get {
                return ResourceManager.GetString("Review_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
